export const Strings = {
  welcome: 'WELCOME',
  eschool: 'eSchool',
  schoolName: 'eSchool',
  avatarText: 'eS',
  pendingDuesAmount: 'AFN. 100',
  pendingDuesDecimal: '.00',
  pendingDuesLabel: 'Pending Dues',
  pendingDuesTitle: 'Pending Dues',
  totalPending: 'TOTAL PENDING',
  pendingDuesSummary: 'Across 1 student · 3 fees',
  assignment: 'Assignments',
  timetable: 'Timetable',
  holidays: 'Holidays',
  exams: 'Exams',
  result: 'Result',
  dueBy: 'Due by 30 Nov 2025',
  overdue: 'Overdue',
  pending: 'Pending',
  studentDues: 'Student Dues',
  feeBreakdown: 'FEE BREAKDOWN',
  menu: 'Menu',
  items: 'items',
  payNow: 'Pay AFN. 100 Now',
  securePayments: 'Secure Payments',
  securePaymentsSub: 'Powered by eSchool Pay · 256-bit SSL',
  tabAll: 'All',
  tabDiary: 'Diary',
  tabAnnouncement: 'Announcement',
  diaryBadge: 'Diary',
  bySchoolAdmin: 'By School Admin',

  profile: 'Profile',
  home: 'Home',
  chat: 'Chat',
  searchChat: 'Search conversations...',
  typeMessage: 'Type a message...',
  schoolAdminOnline: 'School Admin online',
  chatToday: 'Today, 12 Nov',
  chatAnnouncement: 'ANNOUNCEMENT',
  attends: 'Attends',
  attendance: 'Attendance',
  student: 'Student',
  thisMonth: 'This Month',
  present: 'Present',
  absent: 'Absent',
  leave: 'Leave',
  attendanceRate: 'Attendance Rate',
  greatConsistency: 'Great consistency this month',
  seeHistory: 'See History',
  hideHistory: 'Hide History',
  attendanceHistory: 'Attendance History',
  filter: 'Filter',
  unmarked: 'Unmarked',
  exam: 'Exam',
  examOverview: 'Exam Overview',
  totalExams: 'Total Exams',
  averageScore: 'Average Score',
  highestScore: 'Highest Score',
  lowestScore: 'Lowest Score',
  nextExam: 'Next Exam',
  examHistory: 'Exam History',
  recentAcademicResults: 'Recent academic results',
  dateRange: 'DATE RANGE',
  marks: 'MARKS',
  score: 'SCORE',
  passed: 'PASSED',
  failed: 'FAILED',
  downloadPdf: 'Download PDF',
  selectRange: 'SELECT RANGE',
  start: 'START',
  end: 'END',
  clear: 'Clear',
  cancel: 'Cancel',
  apply: 'Apply',
  teachers: 'Teachers',
  classTeacher: 'CLASS TEACHER',
  subjectTeachers: 'SUBJECT TEACHERS',
  message: 'Message',
  dues: 'Dues',
  myProfile: 'My Profile',
  mySyllabus: 'My Syllabus',
  syllabus: 'Syllabus',
  subject: 'Subject',
  complete: 'Complete',
  onTrack: 'On Track',
  completed: 'Completed',
  inProgress: 'In Progress',
  of: 'of',
  topicsCompleted: 'topics completed',
  onlineExams: 'Online Exams',
  liveNow: 'LIVE NOW',
  timeRemaining: 'Time remaining',
  startExam: 'Start Exam',
  marksLabel: 'Marks',
  minLabel: 'min',
  marksLower: 'marks',
  upcomingExams: 'UPCOMING EXAMS',
  completedExams: 'COMPLETED EXAMS',
  scheduled: 'scheduled',
  results: 'results',
  viewDetails: 'View Details',
  viewResult: 'View Result',
  examStartSoon: 'Exam screen will open here.',
  examDetailsSoon: 'Exam details will open here.',
  examResultSoon: 'Exam result will open here.',
  question: 'Question',
  answered: 'answered',
  remaining: 'remaining',
  flagged: 'flagged',
  questionNavigator: 'QUESTION NAVIGATOR',
  tapToJump: 'Tap to jump',
  current: 'Current',
  unanswered: 'Unanswered',
  answeredLegend: 'Answered',
  currentLegend: 'Current',
  unansweredLegend: 'Unanswered',
  onlineClasses: 'Online Classes',
  digitalLibrary: 'Digital Library',
  librarySearchPlaceholder: 'Search books, notes, PDFs...',
  recentlyAdded: 'Recently Added',
  seeAll: 'See All',
  classWiseCategories: 'Class-wise Categories',
  libraryNoResults: 'No resources found.',
  libraryFileComingSoon: 'This file will be available soon.',
  libraryOpenPdf: 'PDF viewer will open here.',
  libraryDownloadStarted: 'Download will start here.',
  libraryDownloadSuccess: 'File downloaded successfully.',
  libraryDownloadFailed: 'Download failed. Please try again.',
  libraryClassResources: 'Class resources list will open here.',
  studentIdCard: 'Student ID Card',
  studentName: 'Student Name',
  studentIdLabel: 'Student ID',
  classAndSection: 'Class & Section',
  rollNumber: 'Roll Number',
  dateOfIssue: 'Date of Issue',
  validUntil: 'Valid Until',
  printIdCard: 'Print ID Card',
  idCardPreviewFront: 'ID CARD PREVIEW · FRONT',
  idCardPreviewBack: 'ID CARD PREVIEW · BACK',
  cardDetails: 'CARD DETAILS',
  flipToBack: 'Flip to Back',
  flipToFront: 'Flip to Front',
  verified: 'Verified',
  authorizedSignature: 'Authorized signature required',
  idCardBackNote:
    'This card is property of E-School. If found, please return to school office.',
  idCardDownloadSoon: 'PDF download will be added here.',
  idCardDownloadSuccess: 'ID card PDF saved successfully.',
  idCardDownloadFailed: 'Could not save ID card PDF.',
  idCardPrintSoon: 'Print option will be added here.',
  idCardPrintFailed: 'Could not open print dialog.',
  classShort: 'CLASS',
  sectionShort: 'SECTION',
  rollShort: 'ROLL NO',
  reportCardReady: 'Report Card Ready',

  studentId: 'Student ID',
  guardian: 'Guardian',
  dateOfBirth: 'Date of Birth',
  classLabel: 'Class',
  section: 'Section',
  onlineClass: 'Online Classes',
  liveNowTab: 'Live Now',
  upcomingTab: 'Upcoming',
  endedTab: 'Ended',
  zoomMeeting: 'ZOOM MEETING',
  liveBadge: 'LIVE',
  joinClass: 'Join Class',
  upcomingSessions: 'UPCOMING SESSIONS',
  viewAll: 'View all',
  recentRecordings: 'RECENT RECORDINGS',
  all: 'All',
  tomorrow: 'Tomorrow',
  setReminder: 'Set Reminder',
  watch: 'Watch',
  download: 'Download',
  endedLabel: 'Ended',
  zoomAppRequired: 'Zoom App Required',
  zoomAppDesc:
    'Install Zoom app for the best class experience. Audio & video work seamlessly.',
  joinClassSoon: 'Join class link will open here.',
  setReminderSoon: 'Reminder will be set here.',
  watchSoon: 'Recording will play here.',
  downloadSoon: 'Download will start here.',
  guardianInfo: 'Guardian Information',
  reportCard: 'Report Card',
  idCard: 'ID Card',
  changePassword: 'Change Password',
  logout: 'Logout',
  settings: 'Settings',
  switchStudent: 'SWITCH STUDENT',
  linked: 'linked',
  appVersion: 'eSchool Parents - v2.4.1',

  fullName: 'Full Name',
  email: 'Email',
  phone: 'Phone Number',
  cnic: 'CNIC Number',
  address: 'Address',
  save: 'Save',

  selectRole: 'Select Your Role',
  roleSubtitle: 'Choose how you want to continue with eSchool',
  parentRole: 'Parent',
  parentRoleDesc:
    "Access your child's academic journey, fees and school updates",
  studentRole: 'Student',
  studentRoleDesc: 'View your classes, exams, attendance and more',
  parentsPortal: 'PARENTS PORTAL',
  welcomeBack: 'Welcome back',
  signInTitle: 'Sign in to your Portal',
  signInDesc:
    "Securely access your child's academic journey and school updates in one place.",
  cnicPlaceholder: 'Enter your CNIC',
  cnicHelper: 'Enter your CNIC as registered with the school',
  signIn: 'Sign In',
  dataSafe: 'Your data is safe and encrypted',
  website: 'www.eSchool.com',

  subjects: 'Subjects',
  myChildren: 'My Children',
  parentAccount: 'Parent Account',
  child: 'Child',
  viewingChild: 'Viewing',
};

export const LINKED_STUDENTS = [
  {
    value: '1',
    label: 'Bilal Khaliq',
    initials: 'AR',
    classBadge: 'Class 7 - B',
    meta: 'Class 7 - B - Roll 12',
  },
  {
    value: '2',
    label: 'Jalal Khaliq',
    initials: 'DR',
    classBadge: 'Class 3 - A',
    meta: 'Class 3 - A - Roll 08',
  },
  {
    value: '3',
    label: 'Aqsa Khaliq',
    initials: 'VR',
    classBadge: 'Class 8 - C',
    meta: 'Class 8 - C - Roll 21',
  },
];

export const EXAM_STUDENTS = [
  {
    value: '1',
    label: 'Bilal Khaliq',
    initials: 'BK',
    classInfo: 'Class 7 - Section B',
    totalExams: '12',
    averageScore: '82',
    highestScore: '96',
    lowestScore: '62',
    nextExamSubject: 'Mathematics',
    nextExamDate: 'Mon, 18 Nov',
    nextExamTime: '09:30 AM',
  },
  {
    value: '2',
    label: 'Jalal Khaliq',
    initials: 'JK',
    classInfo: 'Class 3 - Section A',
    totalExams: '8',
    averageScore: '78',
    highestScore: '91',
    lowestScore: '65',
    nextExamSubject: 'English',
    nextExamDate: 'Wed, 20 Nov',
    nextExamTime: '10:00 AM',
  },
  {
    value: '3',
    label: 'Aqsa Khaliq',
    initials: 'AK',
    classInfo: 'Class 8 - Section C',
    totalExams: '10',
    averageScore: '85',
    highestScore: '98',
    lowestScore: '70',
    nextExamSubject: 'Science',
    nextExamDate: 'Fri, 22 Nov',
    nextExamTime: '11:30 AM',
  },
];

export const EXAM_HISTORY = [
  {
    id: '1',
    subject: 'Mathematics',
    icon: 'calculator-outline',
    date: 'Mar 28, 2025',
    status: 'PASSED',
    marks: '92/100',
    score: '92%',
  },
  {
    id: '2',
    subject: 'English',
    icon: 'book-outline',
    date: 'Mar 15, 2025',
    status: 'PASSED',
    marks: '85/100',
    score: '85%',
  },
  {
    id: '3',
    subject: 'Science',
    icon: 'flask-outline',
    date: 'Mar 5, 2025',
    status: 'PASSED',
    marks: '88/100',
    score: '88%',
  },
  {
    id: '4',
    subject: 'Urdu',
    icon: 'language-outline',
    date: 'Feb 20, 2025',
    status: 'PASSED',
    marks: '76/100',
    score: '76%',
  },
  {
    id: '5',
    subject: 'Islamiat',
    icon: 'library-outline',
    date: 'Feb 10, 2025',
    status: 'PASSED',
    marks: '94/100',
    score: '94%',
  },
  {
    id: '6',
    subject: 'Computer',
    icon: 'desktop-outline',
    date: 'Jan 25, 2025',
    status: 'FAILED',
    marks: '45/100',
    score: '45%',
  },
];
